### PR TITLE
exposing http client for web sockets 

### PR DESCRIPTION
**Pull request by rnewquist**
Solution for certificate pinning for web sockets.
Solves [#34284](https://github.com/dart-lang/sdk/issues/34284)

### CODE REVIEW

**Comment by athomas** [comment]
Please rebase your commits on master and push again. We can only accept PRs on the master branch. The dev branch is autogenerated.

**Comment by rnewquist** [comment]
@athomas do you mean making the changes from master and pushing to master?

**Comment by athomas** [comment]
> @athomas do you mean making the changes from master and pushing to master?

I mean roughly this (I use `fork` as the remote name for your own repo and `upstream` as the remote referring to `dart-lang/sdk` here):

```
git rebase upstream/master
git push # might need -f here
```

Or alternatively:
```
git reset upstream/master --hard # be careful and check that you don't have other changes.
git cherry-pick <hash of commit>
git push # might need -f here
```

Otherwise you can create a new branch tracking master and apply your changes there and open a new PR.

**Comment by athomas** [comment]
Looks like you attempted to merge from dev to master which doesn't work because the merge will include all the commits on dev that aren't on master (and we don't want those).

Let me know if you need help with this and I can try and fix this up.

**Pull request closed without merging**
