### PR TITLE
allow to set enableAssertInitializer with DriverOptions

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
/cc @bwilkerson @pq 

related to art-lang/linter#630

**Review by bwilkerson — APPROVED** [review]

**Comment by pq** [comment]
LGTM.

Thanks!

@bwilkerson : am I right that we'll want to back port this to the 0.1.29 branch?

**Comment by bwilkerson** [comment]
Yes, it will need to be backported to 0.29.

**Comment by a14n** [comment]
I'm not allowed to merge. Could you do it ?
Have I something to do for the backport or will you handle it ?

**Comment by pq** [comment]
Sorry for the slow response!

https://github.com/dart-lang/sdk/pull/29515 👍

**Pull request merged**
