### PR TITLE
Status files updated according buildbot run results

### PR DESCRIPTION
**Pull request by sgrekhov**
Status files updated according buildbot run results

### CODE REVIEW

**Comment by mit-mit** [comment]
@sgrekhov can you look at the conflicts, please?

**Comment by sgrekhov** [comment]
@mit-mit, unfortunately I don't have write access to sdk repository and therefore unable to see the conflicts

**Comment by mit-mit** [comment]
@whesse can you help?

**Comment by sgrekhov** [comment]
Of course I'll help. Please send me file with the conflicts, I'll resolve them and commit it or send it back to you. My email is sgrekhov@unipro.ru

**Comment by whesse** [comment]
I landed this already, temporarily, to get the buildbot output on it.  Since that was 7 days ago, I will now land it again, temporarily.  After one more round of updates, with the output from this run, it should be ready to land permanently.

It would be good to keep this rebased so it lands cleanly.  I can make a pull request to do that.

**Comment by sgrekhov** [comment]
@whesse I've updated .status files according last buildbot results. Please review

**Comment by whesse** [comment]
LGTM.  Merging.

**Pull request merged**
