### PR TITLE
Fix code snippet in Queue.from documentation

### LINKED ISSUE #37943: Typo in documentation of Queue.from constructor
[Here](https://api.dartlang.org/stable/2.4.1/dart-collection/Queue/Queue.from.html) in the following code snippet
```
Queue<SuperType> superQueue = ...;
Queue<SubType> subQueue =
    new Queue<SubType>.from(superSet.whereType<SubType>());
```
I think `superSet` was meant to be `superQueue`.

### PR DESCRIPTION
**Pull request by OsamaElHariri**
Closes #37943

### CODE REVIEW

**Comment by mit-mit** [comment]
Code review: https://dart-review.googlesource.com/c/sdk/+/121641

**Comment by mit-mit** [comment]
Thanks for the contribution! Can you please make a similar fix to the current branch of this library located here? https://github.com/dart-lang/sdk/blob/master/sdk_nnbd/lib/collection/queue.dart

**Comment by OsamaElHariri** [comment]
Done :+1:  @mit-mit

**Comment by athomas** [comment]
This was actually fixed already in https://github.com/dart-lang/sdk/commit/04702d827bbcf51f8f331c23df8508b12b127bf6.

I'm not sure what happened there, but it seems like the issue was fixed independently of this PR. Thanks for your contribution and sorry for the mess.

For posterity:
Because there was no change if this PR was submitted, the Gerrit sync failed (or more accurately was a no op). If the sync had respected the PR's base the Gerrit review would've highlighted the problem (I'll see if that can be fixed). Because GitHub only seems to be able to diff against the PR it incorrectly claims there are changes here. The only way to correct that would be to rebase the PR (which would result in no changes).

**Pull request closed without merging**
