### PR TITLE
Update docs for Map values, keys

### PR DESCRIPTION
**Pull request by sethladd**
Closes https://github.com/dart-lang/sdk/issues/27968

### CODE REVIEW

**Comment by tvolkert** [comment]
LGTM

**Review by kevmoo — CHANGES_REQUESTED** [review]
"break the iteration" is a bit vague here.

I think you mean it'll throw an exception?

**Comment by sethladd** [comment]
I just copied what the higher-level Map docs said.

**Review by kevmoo — APPROVED** [review]
Hrm...okay...

**Pull request merged**
