### PR TITLE
co19/Language test renamed

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Comment by whesse** [comment]
We have a problem in updating co19 now, because it has been forked.  The group updating dartium has created the "integration" branch in co19, with their changes to tests, and the co19 group has updated the names of some of the tests.  The dartium group is committing soon, and will update co19 to point to their branch.  We then need to merge the two co19 branches, and update to the merged co19, including these updates to status files.

Are there more changes to the naming or directories in co19 that affect the status files, or is this it?  I thought it was going to be a bigger change, that would change the names of all of the tests.

So who should be responsible for merging the two branches?  I think this is something that unipro could do, isn't it?

CC: @alan-knight @terrylucas

**Comment by sgrekhov** [comment]
These are all of the renaming changes. At that point we've renamed Language tests only. We (UniPro) will merge the branches and resolve the conflicts. Please let us know as soon as Dartium team commit their changes and we'll do the merge

**Comment by alsemenov** [comment]
UniPro is willing to be responsible for integrating changes from branch  integration into branch master.
But we need to settle two points:
* We need to know whether integration branch is ready for merge.
Please, let us know, when you finish with integration branch, so we 
could start merging.
* Your last commit
 https://github.com/dart-lang/co19/commit/994574dff49c42a6466dc58aeba4e222e9ced618 is strange. It looks like you have forked from recent 
master revision and then have overwritten it with some old revision, 
deleting new tests in folder Language, that were developed during 
summer.
If I am right, could you revert you changes before merge?
Otherwise, we would like to know the reasons for this removal

CC: @alan-knight @terrylucas

**Comment by whesse** [comment]
Yes, we are finished with integration branch.  dart-lang/sdk is using tip-of-tree integration from co19 for its checkout of co19.

I suggest that you do not actually make a merge commit of integration to master, in co19.  We just want the changes from the integration branch put onto master as a commit.  The last two commits on integration are dummy commits, the second is a revert of the first, but we cannot remove them.  So ignore them - your task is to merge new_integration to master.

The last two commits on the integration branch of co19 are there only to fix our mirroring of co19 on chromium.googlesource.com.  We started over on a new branch, without a common history with the integration branch, on a branch called "new integration".  But the mirroring doesn't let us to a force push, to just rename that branch "integration".  We have to do a fake merge with the old integration branch.  The actual merge took the old integration branch unchanged, ignoring the new integration branch.  Then the next commit resets it to the new integration branch.

The actual contents of "integration" and of "new_integration" are identical.  If you did a squash, the adding of the added tests, and their deletion again, would disappear.

You do not have to merge master to integration, only merge the changes on integration into master.
So you do not have to make a merge commit on master bringing the integration branch in.  You only need to make a commit to master that includes all the changes to files that the integration branch makes.  I think this will make the job much easier.

An important thing is that you can make no force pushes to master or integration.  You can only do pushes on top of tip-of-tree, and merges to tip-of-tree.

What I would suggest is squashing all changes to integration since it branched from master into a single commit, on a local branch.  I think that will be a much smaller change than all the changes you have made since that point.  Then simply merge that commit to tip-of-tree master.

In other words, all we want is for the changes in integration branch (not including the fake merge and revert) to be applied to master.  So, since they have the same contents, merging integration to master is the same as merging new_integration to master, so yes I can 'virtually" revert the last two commits to integration, by saying your job is to merge new_integration to master.

The ideal situation at the end is for integration to be unchanged, and for master to have a single new commit on it, which includes all the changes from the branch point of new_integration to new_integration.

Then you have to make the status file changes needed, in dart-lang/sdk, so that it can switch from pulling tip-of-tree integration to pulling tip-of-tree master.  The current status files in sdk work with tip-of-tree integration.  Ignore the integration branch in dart-lang/sdk, only look at master.



On Fri, Sep 18, 2015 at 10:04 AM, Aleksei Semenov <notifications@github.com> wrote:
UniPro is willing to be responsible for integrating changes from branch integration into branch master.
But we need to settle two points:

We need to know whether integration branch is ready for merge. Please, let us know, when you finish with integration branch, so we could start merging.
Your last commit dart-lang/co19@994574d is strange. It looks like you have forked from recent master revision and then have overwritten it with some old revision, deleting new tests in folder Language, that were developed during summer. If I am right, could you revert you changes before merge? Otherwise, we would like to know the reasons for this removal
CC: @alan-knight @terrylucas

—
Reply to this email directly or view it on GitHub.




-- 
William Hesse

**Comment by alsemenov** [comment]
Merging is complete. Please, verify.

Do you need any updates in *.status files?

**Comment by whesse** [comment]
Yes, we need updates in *.status files.
I tried doing it myself, and it is almost impossible for me to find the
renames from the commits - even git diff -M --summary shows many of them as
deletes and creates, rather than renames, and editing the *.status files by
hand is really time-consuming.

I sure hope you have a database of what the old names and new names of
tests are, because then you can update the status files much more
efficiently.


On Mon, Sep 21, 2015 at 9:50 AM, Aleksei Semenov <notifications@github.com>
wrote:

> Merging is complete. Please, verify.
>
> Do you need any updates in *.status files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/pull/24250#issuecomment-141900707>.
>



-- 
William Hesse

**Comment by alsemenov** [comment]
We do not have the database matching old names with new ones. Instead we use git history.
Please, try the following command: 
```
git log   --follow --name-status --find-copies -- <directory_name>
```
For renamed files it prints the new name and the old name on single line. So you can filter the results either by old name or by new name.

BTW, this pull request is about changing test names in *.status files in dartlang/sdk repository.
Could you review it and point out which additional test names should be updated in the *.status files?
If you are satisfied with it, please, integrate it.

CC: @alan-knight @terrylucas

**Comment by whesse** [comment]
A modified version of this pull request has been commited as d524cf407629e37263bc6aa8b17098bd465806fa
 See review at https://codereview.chromium.org/1390533003

**Pull request closed without merging**
