### PR TITLE
Use the new path to the linter package

### PR DESCRIPTION
**Pull request by yyoon**
@zanderso @bwilkerson

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]

**Comment by kevmoo** [comment]
@yyoon can you merge this? If not, @bwilkerson would you do the honors?

**Comment by yyoon** [comment]
@kevmoo I don't have write access here.

**Comment by zanderso** [comment]
I think this was probably already discussed, but I just wanted to note again that in general the version of the package pulled into //dart/third_party/pkg may not agree with the versions of packages pulled into //third_party/dart-pkg.

However, I suppose that you've tried this change out, and it will unblock you until we get a full SDK built in the Fuchsia tree.

**Comment by yyoon** [comment]
Yes. There aren't too many packages that depend on linter right now, and I've tried all these changes locally to make sure the dart analysis works as expected.

**Pull request merged**
