### PR TITLE
[vm/compiler] Update BinaryInt64Op on ARM

### PR DESCRIPTION
**Pull request by clamp03**
Use immediate for AND, OR, XOR, ADD and SUB instruction

### CODE REVIEW

**Comment by clamp03** [comment]
Hi, I am investigating native code quality for ARM AOT. I found that it doesn't use immediate value well for BinaryInt64Op. made a patch for that. 
Could you please review it? Thank you in advance.

**Comment by mraleph** [comment]
Reviewing it here: https://dart-review.googlesource.com/c/sdk/+/200360

Thanks for the contribution 

Our integer arithmetic code generation on 32-bit ARM is rather poor - there are a lot of opportunities to improve it (e.g. narrow the range of integer operations based where appropriate to use 32-bit integers instead of 64-bit integers).

**Comment by mraleph** [comment]
LGTM with the final suggestion on how to avoid some code duplication. See comment on https://dart-review.googlesource.com/c/sdk/+/200360.

**Comment by clamp03** [comment]
> Reviewing it here: https://dart-review.googlesource.com/c/sdk/+/200360
> 
> Thanks for the contribution
> 
> Our integer arithmetic code generation on 32-bit ARM is rather poor - there are a lot of opportunities to improve it (e.g. narrow the range of integer operations based where appropriate to use 32-bit integers instead of 64-bit integers).

Thanks for your comment.
I agree with you. I can find some opportunities where you mentioned. ex) loop index variable add/sub, comparing variable with constant.

**Comment by mraleph** [comment]
Thanks! I will kick off CQ as soon as copybara pulls the latest changes into CL. 

In future I'd recommend to contribute through Gerrit directly if possible because `git cl upload` will  also run various presubmits (e.g. check formatting, run `clang-tidy`, do some linting).

**Comment by clamp03** [comment]
@mraleph Thank you. I will try to contribute through Gerrit directly next time.

**Comment by mraleph** [comment]
Thanks for the contribution, our internal CI infrastructure has detected a number of improvements in code size and performance on ARM devices! (Unfortunately there is no good way to share the numbers because this infrastructure does not have a public interface).

**Comment by clamp03** [comment]
@mraleph I am really happy to hear that. Thank you so much!!!

**Comment by clamp03** [comment]
@mraleph Could you share an overall improvement percentage or number of this patch? (an approximate number is okay.)

**Comment by mraleph** [comment]
Here are some lines from the tracking: 


name | diff | metric​ | target | machine | cpu
-- | -- | -- | -- | -- | --
protobuf_encode_RunTimeRaw | -7.72 % | ​R​u​n​T​i​m​e​R​a​w​ | protobuf-aot | Odroid-C2 | linux-armv7hf

name | diff | metric​ | target | machine | cpu | after | before
-- | -- | -- | -- | -- | -- | -- | --
flutter_gallery_total_size | -0.5026% | CodeSize | flutter_release | | linux-armv7hf | 7953327.00 | 7993499.00

Screenshot 2021-05-21 at 09 45 11
Screenshot 2021-05-21 at 09 44 50

Hope this helps.

**Comment by clamp03** [comment]
@mraleph Thank you. :)

**Pull request closed without merging**
