### PR TITLE
Add "closing labels" to API spec.

### PR DESCRIPTION
**Pull request by DanTup**
@bwilkerson Proposed spec changes for #30285.

Note: This does not include `experimental="true"` because it didn't seem to work on notifications:

```text
Exception: analysis.closingLabels: Unexpected attribute in notification: experimental
#0      ApiReader.checkAttributes.<anonymous closure> (file:///Users/danny/Dev/Google/sdk/pkg/analysis_server/tool/spec/from_html.dart:127:9)
```

It also doesn't include a change to the spec version yet (makes most sense to do this at the end in case other work increases it before this lands) nor the re-generation of files.

If you want to keep these out of master until complete, it may be worth creating a branch and re-targeting this PR there to allow smaller PRs for reviewing.

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]
You'll need to regenerate before committing, but other than that, lgtm.

**Comment by DanTup** [comment]
@bwilkerson Does it need to be in the same commit, or is pushing another changeset to this PR enough (I don't know how your build/testing works or how small you like commits).

Will sort out when back, thanks!

**Comment by bwilkerson** [comment]
A separate commit added to the PR is fine. When the merge is performed it will squash all of the commits, so it doesn't matter how many there were before the merge.

**Comment by DanTup** [comment]
@bwilkerson Cool; I forgot you have the option to quash from PRs too. Files regenerated and pushed.

**Review by bwilkerson — APPROVED** [review]

**Comment by bwilkerson** [comment]
Do you have permission to merge, or should I do it?

**Comment by DanTup** [comment]
@bwilkerson I do *not* have permission, I'm just an outsider! (and probably I don't want the responsibility ;-))

**Pull request merged**
