### PR TITLE
Use "|" as the separator between module path and name.

### PR DESCRIPTION
**Pull request by munificent**
":" is already a path character in Windows. This is why the
dartdevc tests aren't working on Windows. Because they try to do:

-sC:/some/path/blah.dart:blah

And it splits at the first ":". Oops.

### CODE REVIEW

**Comment by jmesserly** [comment]
FYI -- this is possibly a breaking change for build. Can you follow up and fix build scripts if needed?

**Review by jmesserly — CHANGES_REQUESTED** [review]
"|" will break unix shells, right? Are there any other options?

**Comment by munificent** [comment]
How about `=`?

**Review by jmesserly — APPROVED** [review]
sounds good to me!

**Pull request merged**
