### PR TITLE
[vm/ffi] Supporting .address.cast() expression in ffi leaf calls

### PR DESCRIPTION
**Pull request by codesculpture**

### CODE REVIEW

**Comment by mit-mit** [comment]
@codesculpture please see review feedback in https://dart-review.googlesource.com/c/sdk/+/378221

**Comment by codesculpture** [comment]
Sorry @mit-mit , i dint noticed there. Its just a WIP and been discussed with @dcharkes. 
Will look on it, Thanks

**Comment by codesculpture** [comment]
Copybara is commenting twice for everytime it updates, previously it did only once.

Any idea ? @mraleph @dcharkes

**Comment by codesculpture** [comment]
While looking at gerrit, seems one update contains the actual changes and another one contains updated commit message (latest updated time)

Please ignore this if it is intentional.

**Comment by dcharkes** [comment]
(I have already reviewed. Currently waiting for addressing of comments from analyzer team.)

**Comment by codesculpture** [comment]
I will address the comment asap @dcharkes 
Just got some personal work to be done.

**Pull request closed without merging**
