### PR TITLE
Switch to TLS 1.2 as minimum requirement

### PR DESCRIPTION
**Pull request by loganaden**
According to https://tools.ietf.org/id/draft-ietf-tls-oldversions-deprecate-06.txt

### CODE REVIEW

**Comment by kevmoo** [comment]
See https://dart-review.googlesource.com/c/sdk/+/140481

**Comment by kevmoo** [comment]
Thoughts @bkonyi ?

**Comment by bkonyi** [comment]
> Thoughts @bkonyi ?

The change looks simple enough, but I'm not super familiar with that code so I'm going to loop in a couple of others as well on the CL.

**Review by Maniakrzelaza — APPROVED** [review]

**Comment by gustav3d** [comment]
Any progress here ?

**Comment by kevmoo** [comment]
CC @a-siva @vsmenon

**Comment by agilob** [comment]
TLS 1.0 and 1.1. are officially deprecated now https://datatracker.ietf.org/doc/rfc8996/ as of 2021-03-25

**Comment by mit-mit** [comment]
Associated breaking change request: https://github.com/dart-lang/sdk/issues/46875

**Comment by mit-mit** [comment]
Thanks @loganaden for this contribution!

**Pull request closed without merging**
