### PR TITLE
[errors] Fix typo in URL resolution error code.

### PR DESCRIPTION
**Pull request by akbiggs**

### CODE REVIEW

**Comment by mit-mit** [comment]
Thanks for the PR! This is a generated file, so can you please follow the instructions here?
https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/src/error/codes.g.dart#L5

**Comment by bwilkerson** [comment]
Please see my comments on https://dart-review.googlesource.com/c/sdk/+/253824.

**Comment by mit-mit** [comment]
@akbiggs are you expecting to move forward with this fix?

**Comment by akbiggs** [comment]
sorry just saw all this. yes but going to go through gerrit - thanks for the tips

**Pull request closed without merging**
