### PR TITLE
Add innerText field to Element class

### PR DESCRIPTION
**Pull request by luaVolk**
As mentioned in #28303 Dart needs the innerText getter/setter.

This seems like all thats needed.

### CODE REVIEW

**Comment by kevmoo** [comment]
@terrylucas – I think we'll have to do more here, right?

**Comment by mraleph** [comment]
ping?

**Comment by kevmoo** [comment]
@terrylucas  @vsmenon

**Comment by mit-mit** [comment]
This has landed, thanks for contributing @luaVolk

**Comment by terrylucas** [comment]
This would be removed when dart:html is regenereated.  I will add to the appropriate template file and add the missing @JSName('innerText').

**Pull request closed without merging**
