### PR TITLE
Create newsletter index

### PR DESCRIPTION
**Pull request by kwalrath**
Using the GitHub flow, so it's easier to see how it'll look.

### CODE REVIEW

**Review by floitschG — APPROVED** [review]

**Comment by kwalrath** [comment]
@whesse can you give me write access?

**Comment by whesse** [comment]
According to what I can see, you should have write access to the dart-lang/sdk repo.  You are a member of the dart-core-eng group, and have write access to it.  Please let me know what error message you get when you try tocommit.

**Comment by kwalrath** [comment]
I see this:

image

**Comment by whesse** [comment]
OK, I've added you explicitly as a collaborator, but I don't understand why you are getting this warning.  You should be able to write and push as a member of dart-core-eng.  If this doesn't work, let me know if you want me to merge the change.

**Comment by kwalrath** [comment]
I still see the same message. (I tried clearing the cache, but no dice.) Could you please merge the change?

**Review by whesse — APPROVED** [review]

**Comment by whesse** [comment]
You can try landing a change to tools/FAKE_COMMITS to see if the problem persists.

**Comment by whesse** [comment]
Of course we couldn't land this change.  Github is no longer the source of truth for the SDK repo, dart.googlesource.com is.  We need to revert this push, and land it using Gerrit instead.

**Comment by kwalrath** [comment]
Ah, OK. Can you revert it, and I'll figure out how to do the Gerrit dance?

**Comment by whesse** [comment]
No, I can't revert it.  All force pushes to github master are disabled at a level even higher than repo and organization administrator.  So I pushed the change to dart.googlesource.com as well.
Now everything is fine.
It was very dumb of me not to remember the big change to our workflow that I've been implementing for months.

**Comment by kwalrath** [comment]
Thanks for making this happen.

**Pull request merged**
