### PR TITLE
[vm/ffi] Add `Dart_IsNull` in `dart_api_dl.h`

### LINKED ISSUE #48331: Dart_IsNull_DL missing
When converting a `Dart_WeakPersistentHandle` to a `Dart_Handle` with `Dart_HandleFromWeakPersistent_DL`  you get back dart null, if the object has been GC'ed. From the docs:

> Allocates a handle in the current scope from a weak persistent handle.
>
> This will be a handle to Dart_Null if the object has been garbage collected.

However, I need the `Dart_IsNull` to be exposed in the `_DL` api to actually recognise this situation.

I can of course track this "manually" by setting some flag in the finalizer callback, but that seems a bit silly.

### PR DESCRIPTION
**Pull request by blagoev**
fixes #48331

### CODE REVIEW

**Comment by blagoev** [comment]
@dcharkes finally got time to do it. 
Note the tests lookup the function from the dynamic lib instead from the executable.

**Comment by blagoev** [comment]
I have also verified with `dumpbin` that a local build of `ffi_test_functions.dll` actually exposes the function.

**Comment by dcharkes** [comment]
Thanks @blagoev!

I left a review at https://dart-review.git.corp.google.com/c/sdk/+/269742

**Comment by mraleph** [comment]
Public link is https://dart-review.googlesource.com/c/sdk/+/269742 (it's also accessible through Show all checks > import/copybara - Details link)

**Comment by blagoev** [comment]
thanks, will handle the PR review in a sec.

**Comment by dcharkes** [comment]
(Wait, since when do we have internal links for Gerrit? 😒)

**Comment by blagoev** [comment]
@dcharkes PR review handled.

**Comment by dcharkes** [comment]
> @dcharkes PR review handled.

Thanks for the quick reply. I replied with two more documentation nits. I'll merge once addressed.

Thanks @blagoev !

**Comment by blagoev** [comment]
@dcharkes I think did it. Thanks for the quick review

**Pull request closed without merging**
