### PR TITLE
fix errors in file

### PR DESCRIPTION
**Pull request by Rupesh-Darimisetti**
removed few errors in files by replacing the right ones.

### CODE REVIEW

**Comment by Rupesh-Darimisetti** [comment]
@googlebot I signed it!

**Comment by Rupesh-Darimisetti** [comment]
@googlebot I signed it!

**Comment by mraleph** [comment]
Thank you for your contributions, but these don't look like useful changes. 

The change in `PRESUBMIT.py` is not even correct, it breaks the script.

**Comment by Rupesh-Darimisetti** [comment]
hello sir when i try to sign on contributor licence agreement it is showing
me error that the credentials are not given and github token is wrong as
shown below.[image: image.png]

**Comment by mraleph** [comment]
> hello sir when i try to sign on contributor licence agreement it is showing me error that the credentials are not given and github token is wrong as shown below.[image: image.png]

Your image did not attach.

**Pull request closed without merging**
