### PR TITLE
Uri.https and Uri.http constructors queryParams type

### PR DESCRIPTION
**Pull request by jagomf**
Currently `Uri.http` and `Uri.https` factory constructors do not allow for `queryParameters` to be `Map<String, dynamic>`, but only `Map<String, String>`, when in fact the main `Uri` constructor does work with `queryParameters` as `Map<String, dynamic>`.

### CODE REVIEW

**Comment by mraleph** [comment]
Gerrit review at https://dart-review.googlesource.com/c/sdk/+/153182

**Comment by jagomf** [comment]
@mraleph @lrhn anything I can help with so that this goes though?

**Comment by mraleph** [comment]
@jagomf in case you have not seen review comments on Gerrit: this needs CHANGELOG.md entry and tests to land according to @kevmoo comment.

**Comment by jagomf** [comment]
@mraleph I have updated Changelog file (hopefully in the right place).

Regarding tests, they are way far from my Dart knowledge. I hope that someone can contribute so that this inconsistency can be solved.

**Comment by jagomf** [comment]
@mraleph I have updated Changelog file (hopefully in the right place).

Regarding tests, they are way far from my Dart knowledge. I actually can't even think of tests for types inconsistency @kevmoo.

I hope that someone can contribute so that this inconsistency can be solved.

**Comment by mraleph** [comment]
Thanks @jagomf! @lrhn do you think tests are absolutely necessary to land this?

@athomas CopyBara can't sync this into Gerrit. Any idea why?

**Comment by lrhn** [comment]
I want tests, because otherwise it probably doesn't work. (Law of nature: If it isn't tested, it's broken.)

If we land this and someone promises to write test for it quickly, we can probably do it in two steps, but we *must not* release this code without adding tests.

**Comment by athomas** [comment]
@mraleph What is not being synced? You posted the link to the Gerrit review yourself and I can see e.g. the CHANGELOG.md there and the diff looks the same to me? I also only see successful jobs for this PR.

**Comment by mit-mit** [comment]
@lrhn can you provide some guidance to @jagomf regarding how to test this?

**Comment by lrhn** [comment]
I'll add some tests. It shouldn't be much, just checking that it actually works for each constructor.

**Pull request closed without merging**
