### PR TITLE
Support for String.substring negative indexes

### PR DESCRIPTION
**Pull request by urusaich**
#27695

### CODE REVIEW

**Comment by nanodesu88** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by lrhn** [comment]
Thank you for your interest.

We don't have any current plans to change the behavior of index operations to allow negative numbers.

I know it's inconvenient to have to write `s.substring(2, s.length - 2)` instead of just `s.substring(2, -2)`. I can see the lure.

However, it's not without cost. If nothing else, every user will now pay for two more `< 0` checks on every call to `substring`, whether they use it or not (which is so far entirely "not"). There is also the risk of hiding errors when a value is accidentally negative. A negative argument is already a hard-to-catch error because it only gets caught at run-time, we do not have a type for "positive integers".

Also, if we do decide to add the ability to use negative indices, we would do it *everywhere*, not just for `substring`. That makes it a large change affecting user-implementable interfaces (like `List` with its `sublist` and `[]` methods), and it would make existing subclasses no longer satisfy the interface contract when they don't accept the negative arguments. So, not a small change.
Doing it only for a single method is not good for consistency, and could lead users to believe it works elsewhere, which doubles the trouble of errors only being caught at run-time.

So, for now, I think we'll prefer to not change `substring`.

**Comment by nanodesu88** [comment]
> Also, if we do decide to add the ability to use negative indices, we would do it _everywhere_, not just for `substring`. That makes it a large change affecting user-implementable interfaces (like `List` with its `sublist` and `[]` methods), and it would make existing subclasses no longer satisfy the interface contract when they don't accept the negative arguments. So, not a small change.
> Doing it only for a single method is not good for consistency, and could lead users to believe it works elsewhere, which doubles the trouble of errors only being caught at run-time.

Good point of view. I think is a good reason for not adding a ability to use negative indeces. Taken

**Pull request closed without merging**
