### PR TITLE
Corrected the format for VM experiment flag

### PR DESCRIPTION
**Pull request by cv692001**
Done the changes as explained and completed the assigned task  by Correcting the format for VM experiment flag 

 #41676

### CODE REVIEW

**Comment by cv692001** [comment]
Hey @natebosch  , Can you Please help me out and explain me that what is the issue . It will be very nice of you .

**Comment by mit-mit** [comment]
This looks good, thanks for the contribution https://github.com/cv692001.

Approved in https://dart-review.googlesource.com/c/sdk/+/168700,edit

**Comment by cv692001** [comment]
@mit-mit  , can you please explain that you are saying that it is approved but it remains unmerged . Actually I am new to open source contribution nd I am looking forward to contribute in Dart an become comfortable in it . Also it will be very nice of you if you can me out with some issues .

**Comment by mit-mit** [comment]
The change was merged i https://github.com/dart-lang/sdk/commit/ec51b7a866275e84da091c718b7dd172fffcdfe1

**Comment by cv692001** [comment]
Hey @mit-mit , why my PR closed with unmerged commits instead of being approved on github.

**Comment by natebosch** [comment]
This was merged, just not through the github UI. PRs get turned into CLs through a different review system and merged in outside of github. The commit linked above is the one that merges this change, as a squash+merge, not a multi parent merge.

https://github.com/dart-lang/sdk/commit/ec51b7a866275e84da091c718b7dd172fffcdfe1

**Comment by cv692001** [comment]
Thanks @natebosch  , can I use  this https://github.com/dart-lang/sdk/commit/ec51b7a866275e84da091c718b7dd172fffcdfe1  for any future reference in open source contribution or wherever it helps as my first contribution that is merged and approved 👍

**Pull request closed without merging**
