### PR TITLE
Make Element.accept() generic.

### PR DESCRIPTION
**Pull request by alorenzen**

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @scheglov @bwilkerson

**Comment by alorenzen** [comment]
Ping?

**Comment by bwilkerson** [comment]
Sorry about the delay, I missed the first e-mail notification.

I really like the change, but we need to update all of the methods that override the accept method to have the same signature, otherwise we get strong mode errors.

**Comment by alorenzen** [comment]
Ok, I've updated all of the subclasses that I could find (based on analyzer warnings in intellij) for the analyzer package.
Please let me know if there are other packages that would need to be updated in parallel.

**Comment by bwilkerson** [comment]
Unfortunately, there are also a couple of places in the 'analysis_server' package, which is in the same repository as the 'analyzer' package and hence must be updated at the same time.

**Comment by alorenzen** [comment]
I looked, but was unable to find any instances in the 'analysis_server' package. There were plenty of places that called accept(), but none that overrode it.

**Comment by mit-mit** [comment]
@bwilkerson can you elaborate?

**Comment by bwilkerson** [comment]
Sorry about the delay. I often miss e-mails like this, so if I haven't responded within a day, please feel free to send me reminder.

I apologize. I don't know what made me think there were implementations in analysis server; I certainly can't find them now. I can only guess that I selected the wrong method when I looked for other implementations of `accept`.

It definitely lgtm.

**Comment by mit-mit** [comment]
Merging.

**Comment by mit-mit** [comment]
@alorenzen thanks so much for your contribution!

**Pull request merged**
