### PR TITLE
Add missing void in function declarations to avoid warning at build t…

### PR DESCRIPTION
**Pull request by kristofb**
…ime "This function declaration is not a prototype"

*Building an application which includes dart_api.h produces warnings with XCode: 

This function declaration is not a prototype

Only three functions prototypes are missing (void).
.*

---

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks for the contribution! Can you sign the CLA (mentioned above)?

cc @mkustermann

**Comment by mkustermann** [comment]
Thanks for the contribution, @kristofb! Would you be willing to sign the CLA? Then I'd be more than happy to merge the change.

(This warning comes due to `-Wstrict-prototypes` in C compilers (it's not an issue for C++ code))

**Comment by kristofb** [comment]
Hello, sorry

I tried to sign, but first, as my commit is not associated to an email, it says that the UNKNOWN_LOGIN <UNKNOWN_EMAIL> didn't signed, altough it's signed by my github account @kristofb

(first I pushed another PR with my email in the commit, but as it's not a gmail acount, I had similar problem, so I removed the email and pushed a second PR, but gain, problem!)

**Comment by devoncarew** [comment]
Hmm, it may be worth re-creating the PR just to eliminate some of the potential issues (or even authoring a new PR just from the github web UI).

**Pull request closed without merging**
