### PR TITLE
Fix missing redirect for http POST on 307 & 308

### PR DESCRIPTION
**Pull request by bschmalb**
Fixes issue: https://github.com/dart-lang/sdk/issues/54001

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details closed>
<summary> Contribution guidelines:</summary>
- See our [contributor guide](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use dart format.
Note that this repository uses Gerrit for code reviews. Your pull request will be automatically converted into a Gerrit CL and a link to the CL written into this PR. The review will happen on Gerrit but you can also push additional commits to this PR to update the code review.
</details>

### CODE REVIEW

**Comment by bschmalb** [comment]
chore: add extended comment

**Comment by mraleph** [comment]
@bschmalb Please take a moment to sign CLA - otherwise we can't merge your PR. Thanks.

**Comment by brianquinlan** [comment]
I left more detailed comments at https://dart-review.googlesource.com/c/sdk/+/337520 but the TL;DR version is that I don't think that RFC-2616 allows redirects for POST requests, except where the status code is 303.

**Comment by bschmalb** [comment]
As described in the issue https://github.com/dart-lang/sdk/issues/54001 there is a rfc-standart https://www.rfc-editor.org/rfc/rfc7538 that describes the redirect for 307 and 308 status codes. @brianquinlan

**Comment by brianquinlan** [comment]
@bschmalb Let's keep the discussion at https://github.com/dart-lang/sdk/issues/54001

**Comment by mraleph** [comment]
I assume this is stale. Please reopen if not.

**Pull request closed without merging**
