### PR TITLE
Add access-control-allow-* headers

### PR DESCRIPTION
**Pull request by kevin-sakemaer**
cc @kevmoo if you know who can handle this.

### CODE REVIEW

**Comment by kevmoo** [comment]
See https://dart-review.googlesource.com/c/sdk/+/198780

@mit-mit – I'm ambivalent. Completeness is nice, but I feel it's a loosing game to try to add more of these to `dart:io`

**Comment by bkonyi** [comment]
I've got no strong opinion one way or another, so LGTM, but let's get input from @mit-mit or @lrhn before landing?

**Comment by lrhn** [comment]
It's essentially cost-free to add constants if they aren't used.
If someone needs them, I have no problem adding them. Completeness is not a goal, but adequacy is.

**Comment by mraleph** [comment]
@lrhn @bkonyi can somebody plus +1 and +2 Gerrit CL?

**Pull request closed without merging**
