### PR TITLE
Normalize Windows drive letters to uppercase for analysis

### LINKED ISSUE #28895: Analyzer reports: "Invalid override. The type of 'x' isn't a subtype of 'x'"
Copying this from https://github.com/Dart-Code/Dart-Code/issues/261 as I don't think it's specific to Dart Code (however, I can't explain why Atom or DartAnalyzer wouldn't show the same issue).

[Here is a smaller repro than attached to the Dart Code issue](https://github.com/dart-lang/sdk/files/801144/repro.zip), it's basically:

## lib/a.dart
```dart
import 'package:repro/b.dart';

class Renderer
{

}

class Mesh extends Renderable
{
    @override
    void render(Renderer r)
    {

    }
}
```

## lib/b.dart
```dart
import 'package:repro/a.dart';

abstract class Renderable
{
    void render(Renderer r);
}
```

There's also a pubspec with just a name and I've run `pub get`.

The error reported is:

```text
file: 'file:///c%3A/Users/danny/Desktop/repro/repro/lib/a.dart'
severity: 'Error'
message: 'Invalid override. The type of 'Mesh.render' ('(Renderer) → void') isn't a subtype of 'Renderable.render' ('(Renderer) → void').'
at: '11,5'
source: 'dart'
```

There's only one `Renderer` class so it seems like these should be the same and the error is incorrect, however the files reference each other, I'm not sure if that's supported?

The log from the AS server is this:

```text
[11:47:34]: ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[11:47:34]: ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["c:\\Users\\danny\\Desktop\\repro\\repro"],"excluded":[]}}
[11:47:34]: <== {"event":"server.connected","params":{"version":"1.17.0","pid":12036,"sessionId":""}}
[11:47:34]: <== {"id":"1"}
[11:47:34]: <== {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
[11:47:34]: <== {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
[11:47:35]: <== {"id":"2"}
[11:47:35]: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[11:47:35]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\a.dart","errors":[]}}
[11:47:35]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\a.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\a.dart","offset":113,"length":39,"startLine":11,"startColumn":5},"message":"Invalid override. The type of 'Mesh.render' ('(Renderer) → void') isn't a subtype of 'Renderable.render' ('(Renderer) → void').","code":"strong_mode_invalid_method_override","hasFix":false}]}}
[11:47:35]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\a.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\a.dart","offset":113,"length":39,"startLine":11,"startColumn":5},"message":"Invalid override. The type of 'Mesh.render' ('(Renderer) → void') isn't a subtype of 'Renderable.render' ('(Renderer) → void').","code":"strong_mode_invalid_method_override","hasFix":false}]}}
[11:47:35]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\b.dart","errors":[]}}
[11:47:35]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\b.dart","errors":[]}}
[11:47:35]: <== {"event":"analysis.errors","params":{"file":"c:\\Users\\danny\\Desktop\\repro\\repro\\lib\\b.dart","errors":[]}}
[11:47:35]: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
```

### LINKED ISSUE #32042: The argument type 'x' can't be assigned to the parameter type 'x'
I think we've seen this before on Windows and believed it to be imports mixing 'package:' and relative paths, however I've just hit this today on a framework type:

```text
file: 'file:///m%3A/Coding/Applications/flutter/packages/flutter_tools/lib/src/doctor.dart'
severity: 'Error'
message: 'The argument type 'Iterable<DoctorValidator> (M:\Apps\Dart\Dart-2.0.0-dev.20.0\lib\core\iterable.dart)' can't be assigned to the parameter type 'Iterable<DoctorValidator> (M:\Apps\Dart\Dart-2.0.0-dev.20.0\lib\core\iterable.dart)'.'
at: '47,28'
source: 'dart'
code: 'argument_type_not_assignable'
```

Note that the types are the same:

```text
'Iterable<DoctorValidator> (M:\Apps\Dart\Dart-2.0.0-dev.20.0\lib\core\iterable.dart)'
'Iterable<DoctorValidator> (M:\Apps\Dart\Dart-2.0.0-dev.20.0\lib\core\iterable.dart)'
```

The source code is this revision:

https://github.com/DanTup/flutter/commit/601655b413e7f38dc67530a3146ddedced368f19

Originally the `VsCodeValidator.installedValidators` returned a List (not Iterable) but I got an equally confusing message (can't assign the list to an argument of iterable) so I change it to iterable while debugging and then it still complained.

I can try this on my Mac later, but I wouldn't be surprised if this was Windows-only given the previous similar error we had was.

### LINKED ISSUE #32095: Analysis server code reports errors on Windows
It's possible this is related to #28895 and/or #32042 but today I was trying to get the analysis server running on Windows (so I can debug those issues), for the latest code (5ceaa66dfaccb32cf2c5d53bfe80d5dd651598ff) I had 107 errors. They all seem to be "can't assign type x to x"-type errors, like this one:

Analysis sever issues

The reason I'm not sure if this is the same as those others, is that in the message the capitalisation of the drive letter is different, and I think that might be causing it (in some of the others, the paths were cased the same).

I don't know if I'll be able to debug this without being able to run it, but I'll see what I can find.

### PR DESCRIPTION
**Pull request by DanTup**
This fixes #32095, ~~however I'm currently unable to get the tests running locally. I'll continue to work on that, but I'm hoping that creating a PR runs all the tests on CI so we should at least get to see if this (legitimately) broke anything in the meantime?~~

Turns out this also fixes #32042! I can't run the latest analyzer code against a version of the SDK that the flutter_tools is happy with, however I rolled my analyzer code back to `2.0-dev.22` and repro'd this error, then applied the same changes from this PR to that version, and the errors went away.

Turns out to also fix #28895!

@bwilkerson

### CODE REVIEW

**Comment by DanTup** [comment]
Oh, looks like there's no CI build for the PR... I'll continue working on getting the tests running locally!

**Comment by DanTup** [comment]
I was running the wrong tests here (analysis_server, but the change is in analyzer). Analyzer tests all pass both before/after this change:

```text
02:46 +22943: All tests passed!
```

**Comment by bwilkerson** [comment]
See https://dart-review.googlesource.com/c/sdk/+/40720 for review comments.

**Comment by DanTup** [comment]
@bwilkerson 

>  you can either click the button labeled "CQ Dry Run" 

Where should that appear? I can't see it but don't know if that might be permission related (I have logged in as danny @ tuppeny...) or because you've already clicked it?

Should I be using Gerrit to raise reviews for things? If so, are there any notes on the process for raising a review once a PR is sent?

**Comment by bwilkerson** [comment]
I'll send you an e-mail where we can have a process discussion. Seems more appropriate.

**Pull request closed without merging**
