### PR TITLE
Fix Socket remoteAddress obtaining on Win32 #51778

### PR DESCRIPTION
**Pull request by slonm**
Looks `getpeername()` is broken when it used after `AcceptEx()`. I found a couple mentions of such issue but it's strange that they are pretty old:

https://www.codeproject.com/Messages/540371/Re-Win2K-AcceptEx-amp-amp-getpeername
https://alt.winsock.programming.narkive.com/ZUX8KVbu/so-update-accept-context-usage

I've implemented the workaround and call `GetAcceptExSockaddrs()` instead of getpeername() immediately after socket connection accept.

Now Unit test `tests\standalone_2\io\socket_info_ipv6_test.dart` is passed without errors.

### CODE REVIEW

**Comment by slonm** [comment]
Initial issue #51778

**Comment by mit-mit** [comment]
Hi @slonm thanks for the contribution; can you please rebase it?

**Comment by slonm** [comment]
Hi @mit-mit, I've resolved conflict but not sure whether I've done things right regarding rebasing. Let me know if there is something wrong

**Comment by mit-mit** [comment]
Thanks. Stay tuned for comments in the dart-review link.

**Comment by brianquinlan** [comment]
@slonm That's up to you. There are two ways that we can go here:

1. You address the comments in the code review and, after we reach a consensus, we commit your change.
2. We abandon your pull request, I recreate it and then send it to another Dart developer for review.

Let me know which you'd prefer.

**Comment by slonm** [comment]
Performed code review. Agreed with most of suggestions

**Pull request closed without merging**
