### PR TITLE
[front-end] fix bug in BodyBuilder 

### PR DESCRIPTION
**Pull request by lfkdsk**
https://github.com/dart-lang/sdk/issues/42997

@mraleph 

> Also, how to construct tests that generate AmbiguousBuilder and catch error?

### CODE REVIEW

**Comment by mraleph** [comment]
Thanks for the contribution. 

Gerrit review here: https://dart-review.googlesource.com/c/sdk/+/157941

I have forwarded it to the right people on the CFE team for review - they should also be able to help you with how to create a regression test.

**Comment by johnniwinther** [comment]
Do you have a small (self contained) repro for the crash? If so, normally we add this as an "expectation test" (in `pkg/front_end/testcases/general/`). This is a bit involved but I you (already) have a small repro I can add it to the CL.

**Comment by lfkdsk** [comment]
https://github.com/lfkdsk/dummy_51752 I created such a Flutter project as described in issues.

**Comment by johnniwinther** [comment]
Thanks. I'll try to make it self-contained (not needing the flutter import) and add it to the CL.

**Pull request closed without merging**
