### PR TITLE
minor changes to comments and strings

### PR DESCRIPTION
**Pull request by guillermooo**
A handful of potential mistakes I've found while reading the code to update the api generator for Python.

### CODE REVIEW

**Comment by guillermooo** [comment]
@googlebot I'll be shocked if you understood this, but my Gmail account says Google has a CLA of mine on record dating from 2014.

**Comment by sethladd** [comment]
cc @bwilkerson

**Comment by bwilkerson** [comment]
LGTM! Thanks for the changes.

**Comment by sethladd** [comment]
@bwilkerson let me know if you need any help merging this. There's also these instructions which make the end result a little nicer: https://github.com/dart-lang/sdk/wiki/WORKING---Git-and-Github-instructions

**Comment by bwilkerson** [comment]
Merged via https://github.com/dart-lang/sdk/commit/dee2389549060a5e5f30a7fb560152c5cdecac9d

**Pull request closed without merging**
