### PR TITLE
Changed Minimum Limit for Trimming File or Dir Path in Windows  

### PR DESCRIPTION
**Pull request by codesculpture**
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.

Note that this repository uses Gerrit for code reviews. Your pull request will be automatically converted into a Gerrit CL and a link to the CL written into this PR. The review will happen on Gerrit but you can also push additional commits to this PR to update the code review.
</details>

Fix of https://github.com/dart-lang/sdk/issues/54386

### CODE REVIEW

**Comment by codesculpture** [comment]
> I think we need to consider relative path. Relative path can be less than 3 in length.
> 
> ```dart
>   final dir = Directory(r'a');    <-- this is relative path
>   final dir = Directory(r'a/');   <-- this PR strips last separator?
>   final dir = Directory('');  <-- current directory  
> ```

Yes you are correct @glanium , @mraleph pointed this same in discord and had a new commit which only have the 3 char limit on absolute path

**Comment by codesculpture** [comment]
_Phew_ windows(dart-sdk-windows-try) tests are green 😀

**Comment by mraleph** [comment]
@codesculpture that one does not actually run any tests. I added vm-win-release-x64-try manually. 

(Normally I would have just added `Cq-Include-Trybots: luci.dart.try:vm-win-release-x64-try` footer to make sure Windows will run but when you make a CL through PR integration that's not possible because AFAIK Copybara would just clobber CL description every time cc @athomas @sortie )

**Comment by codesculpture** [comment]
If everything work normal when i directly make a cl (i thought non-googlers cant do this, is it?)
`
# Upload a CL, add reviewers from OWNERS files, and allow automatic submission. git cl upload --send-mail --r-owners --auto-submit
`
Got this from BUILDING.md

**Comment by mraleph** [comment]
@codesculpture `git cl upload` should certainly work just fine for non-Googlers. Maybe some of these flags `--send-mail --r-owners --auto-submit` don't work - but they are not really necessary. `git cl upload` (without any flags) should be just enough.

**Comment by codesculpture** [comment]
Windows is green 🟢

**Comment by codesculpture** [comment]
> @codesculpture `git cl upload` should certainly work just fine for non-Googlers. Maybe some of these flags `--send-mail --r-owners --auto-submit` don't work - but they are not really necessary. `git cl upload` (without any flags) should be just enough. 

Alright will do that instead of making pr @mraleph . Thank you so much for the help and guidance !

**Comment by athomas** [comment]
> > @codesculpture `git cl upload` should certainly work just fine for non-Googlers. Maybe some of these flags `--send-mail --r-owners --auto-submit` don't work - but they are not really necessary. `git cl upload` (without any flags) should be just enough.
> 
> Next time, Alright will do that instead of making pr @mraleph . Thank you so much for the help and guidance !

Did the flags actually not work or was it just never tried? AFAIK these flags work for non-Googlers as well. If not, please open an issue.

@parlough, I believe these work for you?

**Comment by codesculpture** [comment]
I dint tried @athomas , i just assumed that it would not. Sorry for that and also i mentioned

**Comment by parlough** [comment]
> @parlough, I believe these work for you?

Yeah they work fine as far as I've experienced. I prefer to manually pick reviewers but I've seen others rely on the `--r-owners` flag and it work.

> I dint tried athomas , i just assumed that it would not. Sorry for that and also i mentioned.

No worries! This PR through GitHub works too and is extremely appreciated! Thank you.

If you do want to try Gerrit through `git cl upload` next time though and have any problems, please open an issue :)

**Comment by codesculpture** [comment]
Thanks for the info @parlough

**Comment by brianquinlan** [comment]
I made a few minor comments at https://dart-review.googlesource.com/c/sdk/+/345201

**Comment by codesculpture** [comment]
Thanks for the comments @brianquinlan , Resolved it kindly check

**Comment by codesculpture** [comment]
This is just a question from my curiosity is there anyway to move the comment from unresolved status to resolved in gerrit, this can done in github by just clicking "Resolve Conversation". Since brian made few comments i actually resolved and made commits also i need to make the comments to "resolved" status in gerrit.

**Comment by mraleph** [comment]
@codesculpture you can respond to comments in the UI and there will be a checkbox to mark it resolved (usually you can just click done). Then you press a button to send all your responses (which are by default stores like drafts and only visible to you).

**Comment by codesculpture** [comment]
Thanks @mraleph , will look on that

**Comment by brianquinlan** [comment]
Two more super small nits: https://dart-review.googlesource.com/c/sdk/+/345201

**Comment by codesculpture** [comment]
> Two more super small nits: https://dart-review.googlesource.com/c/sdk/+/345201

Sorry, I planned to include the [link](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats) u shared, but ended up i just visited the link and read but forget to add in the code and commit. 
Resolved Now @brianquinlan

**Comment by brianquinlan** [comment]
Now one more small nit ;-) One of the problems with using the github workflow is that you don't get the `dart format` presubmit check.

We (meaning the Dart team) should fix that.

**Comment by codesculpture** [comment]
I can run that manually this time, well in morning (i live in GMT+5:30) its mid night here

**Comment by codesculpture** [comment]
Done running `dart format` and resolved comments @brianquinlan

**Pull request closed without merging**
