### PR TITLE
37793 documentation update for list

### PR DESCRIPTION
**Pull request by wootenlatwit**
Referencing #37793 
Updated so that the comments no longer point to a deprecated collection. It seems ready to be merged. Let me know if I need to sign any CLA or make additional changes.

### CODE REVIEW

**Comment by Kiddoe** [comment]
@googlebot I signed it!

**Comment by mit-mit** [comment]
Thanks for the contribution! Currently -- as we're implementing non-nullable -- our core libs are forked, so can we please have a similar fix in the fork here? https://github.com/dart-lang/sdk/tree/master/sdk_nnbd

**Comment by Kiddoe** [comment]
> Thanks for the contribution! Currently -- as we're implementing non-nullable -- our core libs are forked, so can we please have a similar fix in the fork here? https://github.com/dart-lang/sdk/tree/master/sdk_nnbd

Alright, thanks for the feedback! I will get that fixed.

**Comment by mit-mit** [comment]
@wootenlatwit are you still working on this?

**Comment by vladdoster** [comment]
> @wootenlatwit are you still working on this?

I was helping him through this, but I don't think he is interested any longer. I have done the proposed fix in the fork in PR #40235.

**Comment by vladdoster** [comment]
@googlebot I signed it!

**Pull request closed without merging**
