### PR TITLE
Change async stubbing to use thenAnswer

### PR DESCRIPTION
**Pull request by alanrussian**
Mockito now prohibits calling thenReturn with Futures and Streams. dart-lang/build#4833

### CODE REVIEW

**Comment by devoncarew** [comment]
@mk13 @bwilkerson @scheglov 

Is pkg/analysis_server_client used? I see the initial commit, but am not sure if anything in the repo was updated to use it. We may consider just removing this package.

**Comment by bwilkerson** [comment]
I believe that Max is using it, but he can tell you for sure. In either case, this seems like a reasonable change.

**Comment by alanrussian** [comment]
I spoke with @keertip and was recommended to ask @mk13 to submit this change. Max, are you able to do this? If so, would you like for me to close this pull request or would you like to modify this one?

**Comment by mit-mit** [comment]
Closing; this appears to be stale

**Pull request closed without merging**
