### PR TITLE
Fixes #34980 by propagating errors from task.cancel() through onTimeout.

### LINKED ISSUE #34980: Get unexpected [NoSuchMethodError] when [connectionTimeout] is set on [HttpClient]
I've found that if `connectionTimeout` is set on `HttpClient` and is shorter than the system level timeout, an unexpected `NoSuchMethodError` will be thrown instead of a `SocketException` described in the document when a connection exceeds this timeout.

After investigating, I find that this might be a bug in Dart SDK.

https://github.com/dart-lang/sdk/blob/f4ce2c5749f3f27cc84140c8fd330079ad90ccdd/sdk/lib/_http/http_impl.dart#L1943-L1949

The connection timeout is implemented using `Future.timeout`, but no error is thrown in the `onTimeout` function. This will cause the returned future(`socketFuture`) to be finished with `null`. Then the `called on null` exception will be thrown in the future's callback.

https://github.com/dart-lang/sdk/blob/f4ce2c5749f3f27cc84140c8fd330079ad90ccdd/sdk/lib/_http/http_impl.dart#L1952

### Demo

```
import 'dart:io';

main(List<String> args) async {
  final client = new HttpClient();

  // CRITICAL
  // Comment this line and the request will be finished with a
  // [SocketException] caused by system level timeout.
  // If a custom connectionTimeout is set and is shorter than
  // the system timeout, an unexpected [NoSuchMethodError] will
  // be thrown.
  client.connectionTimeout = new Duration(microseconds: 1);

  // expected [SocketException] instead of [NoSuchMethodError]
  await client.getUrl(Uri.parse("http://10.255.255.1"));
}

```

Result:

```
Unhandled exception:
NoSuchMethodError: The method 'setOption' was called on null.
Receiver: null
Tried calling: setOption(Instance of 'SocketOption', true)
#0      main (file:///Users/microdog/Workspace/git/dart_http_timeout_demo/main.dart:15:3)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Result without connectionTimeout set:

```
Unhandled exception:
SocketException: OS Error: Operation timed out, errno = 60, address = 10.255.255.1, port = 53232
#0      main (file:///Users/microdog/Workspace/git/dart_http_timeout_demo/main.dart:15:3)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

### Dart SDK Version:

```
Dart VM version: 2.1.0-dev.7.1.flutter-b99bcfd309 (Wed Oct 10 20:19:14 2018 +0000) on "macos_x64"
```

### PR DESCRIPTION
**Pull request by jbdeboer**
Adds a test demonstrating the issue.

### CODE REVIEW

**Comment by jbdeboer** [comment]
Review at https://dart-review.googlesource.com/c/sdk/+/9716

**Comment by sortie** [comment]
Hi @jbdeboer, sorry about the delay, it has been very hectic on my end. I'm going to be unavailable, so @athomas, can you assign another reviewer?

**Comment by ulidtko** [comment]
Come on guys, this is another trivial one-line fix for an obvious problem (null-pointer dereference, the dart way haha), plus a crystal-clear one-page test; just reading through #34980 gives enough context to conclude this line of code was obviously missed by mistake; why does it take so long to review this?

If my word means anything: **LGTM**, go ahead, merge.

[Another single-line patch](/dart-lang/sdk/pull/36038) (by myself truly) has been sitting more than a month in review. Is Dart SDK having an organizational/process bottleneck of some sort?

**Comment by sortie** [comment]
Hi @jbdeboer, now that I'm back from vacation and attending a conference, I had the time review your code at <https://dart-review.googlesource.com/c/sdk/+/97180>. Can you update the code according to my suggestions?

@ulidtko Just because a change is tiny doesn't mean it's trivial to review or that the review should be rushed and in this case I was away from the office for a while. For instance, the proposed fix for this bug was incomplete and didn't work. The test hung at the end. I have a number of other important tasks going on as I am only part time on dart:io so there may be delays.

**Comment by jbdeboer** [comment]
@sortie could you describe how you are running the test? I am unable to
reproduce the issues you are seeing.

**Comment by sortie** [comment]
Hi, I built `tools/build.py -m release -a x64 runtime` on Linux and then ran `out/ReleaseX64/dart 
tests/standalone_2/io/http_connection_timeout_test.dart`.

**Comment by jbdeboer** [comment]
Thanks. I'll find some time to update this PR.

**Comment by sortie** [comment]
Hi, any update?

**Comment by mit-mit** [comment]
Closing as unactionable

**Comment by sortie** [comment]
This issue was fixed in 63a1478f5f138df31a83dc6c4d286b76c908de2d.

**Pull request closed without merging**
