### PR TITLE
Added pubspec.yml File

### PR DESCRIPTION
**Pull request by RajChowdhury240**

### CODE REVIEW

**Comment by Rajchowdhury420** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
Hey @Rajchowdhury420 – what are you trying to do here?

**Comment by Rajchowdhury420** [comment]
PR

**Comment by kevmoo** [comment]
> PR

Clearly. But for what purpose?

**Comment by mit-mit** [comment]
Closing as unactionable

**Pull request closed without merging**
