### PR TITLE
Move the dev_compiler strong mode tests into sdk/tests/.

### PR DESCRIPTION
**Pull request by munificent**
Sending this out as a pull request because Reitveld apparently can't handle a patch this big...

DDC's codegen test copies those files to a local "gen" directory so
that it can do stuff like splitting out the multitests before it
compiles them to JS.

I left all of that alone, so the rest of DDC's test infrastructure is
unchanged. The very first step that builds the "gen" directory just
copies from sdk/tests/..._strong/... instead and the rest is good to go.

I did not move not_yet_strong_tests.dart somewhere more accessible yet
because I'm not sure if kernel needs it or where it should go.

I did not create any status files because DDC doesn't need them and
there are no test suites for the new directories for the other
platforms.

### CODE REVIEW

**Comment by munificent** [comment]
Fixes #27992.

**Comment by vsmenon** [comment]
lgtm - seems travis is unhappy though on a couple tests for some reason.

**Comment by asgerf** [comment]
It seems the line ending encoding was changed for some tests that rely on a specific encoding (I believe it affects multiline string literals).

Otherwise LGTM, and thanks!

**Comment by munificent** [comment]
> It seems the line ending encoding was changed for some tests that rely on a specific encoding (I believe it affects multiline string literals).

Oops, yeah, I think Git renormalized them since it thinks they are new files. I'll fix that.

I think that's what's breaking Travis too.

**Pull request merged**
