### PR TITLE
Fix the server name cannot be set when SNI SSL/TLS request causes handshake failure or request error

### PR DESCRIPTION
**Pull request by chansLam**
BUG:
The following error occurs when using a server without domain name resolution to make an SNI request:
Unhandled exception:
HandshakeException: Connection terminated during handshake

### CODE REVIEW

**Comment by mit-mit** [comment]
Review CL is https://dart-review.googlesource.com/c/sdk/+/243980

**Comment by devoncarew** [comment]
@chansLam - there is some review feedback in https://dart-review.googlesource.com/c/sdk/+/243980 (we don't use github reviews directly for the sdk repo, but can copy the PRs into our review system).

**Comment by brianquinlan** [comment]
Hi, I made some comments on https://dart-review.googlesource.com/c/sdk/+/243980 if you are still looking at this.

**Comment by mit-mit** [comment]
No reply, closing as assumed stale

**Pull request closed without merging**
