### PR TITLE
Update some dartdoc comments in list.dart

### PR DESCRIPTION
**Pull request by killermonk**
Fixing a typo and adding a reference to a function argument

### CODE REVIEW

**Comment by mit-mit** [comment]
Code review in https://dart-review.googlesource.com/c/sdk/+/156163

**Comment by mit-mit** [comment]
@killermonk thanks for the contribution, please review comments in above linked code review

**Comment by mit-mit** [comment]
Closing as assumed stale; above comments were not answered

**Comment by killermonk** [comment]
@mit-mit Sorry, missed the email with your comments. Would you like me to address them and re-open this?

**Comment by mit-mit** [comment]
Sounds good, reopening

**Comment by killermonk** [comment]
@mit-mit it looks like most of the changes from this PR got put in at some other point for something. I've created https://github.com/dart-lang/sdk/pull/44404 to capture the comments you left before for the double spacing issue.

**Pull request closed without merging**
