### PR TITLE
extend INVALID_NULL_AWARE_OPERATOR for extensions on nullable

### PR DESCRIPTION
**Pull request by a14n**
Following up on https://github.com/dart-lang/linter/pull/3379#discussion_r867192583 to add a warning when using null aware operator with a member defined in an extension on nullable type.

```dart
extension on String? {
  bool get isNullOrEmpty {
    var self = this;
    return self == null || self.isEmpty;
  }
}

main() {
  String? s = null;
  s?.isNullOrEmpty; // WARN here
  s.isNullOrEmpty; // OK
}
```

### CODE REVIEW

**Comment by a14n** [comment]
https://dart-review.googlesource.com/c/sdk/+/243939

**Comment by albertms10** [comment]
The code block in the description contains syntax issues. One way to go may be:

```dart
extension on String? {
  bool get isNullOrEmpty => this == null || this!.isEmpty;
}
```

**Comment by a14n** [comment]
@albertms10 Thanks for letting me know. I updated the snippet.

**Comment by a14n** [comment]
Closing to migrate to linter.

**Pull request closed without merging**
