### PR TITLE
Homebrew cleanup

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
ping, @whesse

**Review by whesse — APPROVED** [review]

**Comment by whesse** [comment]
This doesn't work unless you add the path to update_homebrew.lib in ../../../.packages

**Comment by whesse** [comment]
And discovery commons isn't in third-party/pkg.

Reverting.

**Comment by whesse** [comment]
OK, not reverting, but this app requires running pub get in the package directory (tools/apps/update_homebrew), just like the previous version did.

**Comment by kevmoo** [comment]
😄

**Pull request merged**
