### PR TITLE
`KeywordToken`: Change `keyword` field to a getter over `type`

### PR DESCRIPTION
**Pull request by gmpassos**
Reduce `KeywordToken` memory usage by changing the `keyword` field to a getter over `type as Keyword`.

---

- [✅] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

### CODE REVIEW

**Comment by gmpassos** [comment]
> ... a build failure which blocked landing.

Fixed 👍

**Comment by kevmoo** [comment]
Nice find, @gmpassos !

**Comment by gmpassos** [comment]
@kevmoo

I'm conducting some optimization experiments with the analyzer and analysis_server packages, by the way.

If I achieve any significant improvements, I will submit a PR.

Thx for the fast merge!

**Comment by gmpassos** [comment]
@kevmoo @mraleph 

FYI:
https://github.com/gmpassos/sdk/tree/optimize-analyzer

**Pull request closed without merging**
