### PR TITLE
Websocket connect, clear error response

### PR DESCRIPTION
**Pull request by philos3**
Update websocket_impl.dart

It is usefull with more detail for "Connection was not upgraded to websocket error "

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.

Note that this repository uses Gerrit for code reviews. Your pull request will be automatically converted into a Gerrit CL and a link to the CL written into this PR. The review will happen on Gerrit but you can also push additional commits to this PR to update the code review.
</details>

### CODE REVIEW

**Comment by devoncarew** [comment]
@philos3 - thanks for the contribution! Before we can accept it you'll need to sign the CLA at https://cla.developers.google.com/.

Also, can you update the description of the PR to describe more what this PR is trying to accomplish. cc @brianquinlan

**Comment by brianquinlan** [comment]
I left some feedback at https://dart-review.googlesource.com/c/sdk/+/313042

**Comment by mraleph** [comment]
@philos3 would you like to address @brianquinlan's comments or should we close this PR?

**Comment by brianquinlan** [comment]
@mraleph Could we keep this open for now? Let's say that, if @philos3 isn't responsible by Monday, then I'll complete this change.

**Review by JoaoVitorAmorim — APPROVED** [review]

**Comment by JoaoVitorAmorim** [comment]
Approved @philos3

**Comment by mraleph** [comment]
> @mraleph Could we keep this open for now? Let's say that, if @philos3 isn't responsive by Monday, then I'll complete this change.

The deadline has passed, so it is on your plate now :)

**Comment by brianquinlan** [comment]
It's on my plate. Adding the messages was easy - writing tests for all the failure variations is hard ;-)

**Comment by mit-mit** [comment]
Any updates @brianquinlan ?

**Comment by vsmenon** [comment]
gentle ping

**Comment by brianquinlan** [comment]
@mit-mit @vsmenon 

Is this a priority? The original PR doesn't have tests so isn't mergable as-is. I can write the tests myself if getting this in is important.

**Comment by mit-mit** [comment]
Given we're just updating a status message, perhaps we can exempt this one. wdyt Vijay?

**Comment by brianquinlan** [comment]
The PR outputs the entire response message in the error - this could be arbitrarily large.

I have a modified version of the PR that decodes the error in more detail without including the entire response body:

```diff
-      if (response.statusCode != HttpStatus.switchingProtocols ||
-          connectionHeader == null ||
-          !connectionHeader.any((value) => value.toLowerCase() == "upgrade") ||
-          response.headers.value(HttpHeaders.upgradeHeader)!.toLowerCase() !=
-              "websocket") {
-        return error("Connection to '$uri' was not upgraded to websocket");
-      }
+      if (response.statusCode != HttpStatus.switchingProtocols) {
+        return error("Unexpected status code: ${response.statusCode}");
+      }
+      if (connectionHeader == null) {
+        return error("Response did not contain a 'connection' header");
+      }
+      if (connectionHeader.first.toLowerCase() != "upgrade") {
+        return error(
+            "Unexpected 'connection' header: ${connectionHeader.first}");
+      }
+     if (upgradeHeader == null) {
+       return error("Response did not contain an 'upgrade' header");
+     }
+     if (upgradeHeader.first.toLowerCase() != "websocket") {
+       return error("Unexpected 'upgrade' header: ${upgradeHeader.first}");
+     }
+     if (acceptHeader == null) {
+       return error(
+           "Response did not contain a 'Sec-WebSocket-Accept' header");
+     }
```

But writing tests for this is not trivial and it didn't seem worth it. @mit-mit if there is some reason why this should be a priority (e.g., people are complaining about error messages) then just let me know.

**Comment by mraleph** [comment]
I assume this is stale. Please reopen if not.

**Comment by talp-flytrex** [comment]
@philos3 @mraleph 
Any update on this?
Adding the status code to the error message will help handling the error properly.

**Pull request closed without merging**
