### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by polina-c**
Move tool configuration to separate section to make it easier to discover.

### CODE REVIEW

**Comment by mraleph** [comment]
Added few comments to https://dart-review.googlesource.com/c/sdk/+/230953

**Comment by mit-mit** [comment]
Kind reminder @polina-c, please look at the feedback in the review

**Comment by mraleph** [comment]
@mit-mit we have a separate thread going about this CL.

**Comment by polina-c** [comment]
Submitted the changes in CL: https://dart-review.googlesource.com/c/sdk/+/230959

**Pull request closed without merging**
