### PR TITLE
Document that writeAsBytes truncates values beyond 0..255

### PR DESCRIPTION
**Pull request by eseidel**
I just ran into this myself, no sense in anyone else having to hit this issue again.

---

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.

Note that this repository uses Gerrit for code reviews. Your pull request will be automatically converted into a Gerrit CL and a link to the CL written into this PR. The review will happen on Gerrit but you can also push additional commits to this PR to update the code review.
</details>

### CODE REVIEW

**Comment by eseidel** [comment]
Potentially could also point to https://api.flutter.dev/flutter/dart-typed_data/ByteData-class.html for handling multi-byte values.

**Comment by eseidel** [comment]
The last sentence could be skipped or converted to hex, e.g. For example, `256` is treated as `x00`, `257` as `x01`, `-1` as `xFF`, etc.

**Comment by mraleph** [comment]
(review comments from @lrhn are available in Gerrit)

**Comment by eseidel** [comment]
More trouble than it's worth to finish, closing.

**Comment by brianquinlan** [comment]
I'll land this for you sometime next week.

**Comment by eseidel** [comment]
Kind of you. Sorry to not follow through.

**Pull request closed without merging**
