### PR TITLE
Remove unnecessary null checks, now that null-safety is mandatory

### PR DESCRIPTION
**Pull request by mnordine**
See https://github.com/dart-lang/sdk/issues/40614

Seems this should have been part of Dart 3 release.

*Thanks for your contribution! Please replace this paragraph with a description of what this PR is changing or adding and why. List any relevant issues, and review the contribution guidelines below.*

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

#### Contribution guidelines:

- See our [contributor guide](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.

Note that this repository uses Gerrit for code reviews. Your pull request will be automatically converted into a Gerrit CL and a link to the CL written into this PR. The review will happen on Gerrit but you can also push additional commits to this PR to update the code review.

---

### CODE REVIEW

**Comment by devoncarew** [comment]
@lrhn for review (note that this PR should be reviewed / landed using the associated gerrit CL).

**Comment by lrhn** [comment]
We still have a few cases of pre-2.12 code being run against the current SDK code, for annoying technical reasons.
I guess removing the checks should be safe enough. The existing code is presumably safe, so as long as no new pre-2.12 code is written, we should not have any needs for catching newly developed bugs.

**Comment by mraleph** [comment]
@lrhn we should either land it or close it.

**Comment by lrhn** [comment]
Or wait until we've gotten rid of all internal non-sound-null-safe code, which is what I'm leaning towards.
This is exactly the kind of error which will show up even in null-safe code if it's running in non-sound-null-safe mode.

(The alternate point is that the throw has been there for ages now, so no code is currently running which would hit it. Nobody will write *new* non-null-safe code, or add new non-sound null safe projects, so it *is* safe to remove the checks now. In either case, it needs to be merged to head.)

**Comment by vsmenon** [comment]
@lrhn - can we either land or close this?

**Comment by mit-mit** [comment]
I'm afraid this has gone stale. We were unfortunately not in a position to take this when it was submitted, and not that we're ready, the code has "drifted" too far in the meantime.

**Pull request closed without merging**
