### PR TITLE
Remove optional new keyword when extracting widget

### PR DESCRIPTION
**Pull request by cbenhagen**

### CODE REVIEW

**Comment by athomas** [comment]
Gerrit review is here: https://dart-review.googlesource.com/c/sdk/+/119423

**Comment by cbenhagen** [comment]
@athomas Sorry I completely forgot about the tests. I updated them now and they pass locally. Do you want me to squash the two commits?

**Comment by mraleph** [comment]
@cbenhagen commits are automatically - we land all things through Gerrit (which this PR is automatically synced to).

**Comment by scheglov** [comment]
Thank you!

**Pull request closed without merging**
