### PR TITLE
Update list.dart

### LINKED ISSUE #37262: Explain that List.== does not compare contents, link to collections.ListEquality
I had difficulty finding out how to compare the contents of two List objects.  My first stop was the List.== operator:
https://api.dartlang.org/stable/2.3.2/dart-core/List-class.html#operators
That page links to Object.== operator.  I spent 15 minutes finding the [answer](https://stackoverflow.com/a/22333042).  How about updating the docs to helpfully state that List.== does not compare contents, but this can be done with the collections.ListEquality class?

### PR DESCRIPTION
**Pull request by MetalDent**
This PR fixes #37262.

### CODE REVIEW

**Comment by mit-mit** [comment]
Review in https://dart-review.googlesource.com/c/sdk/+/108180

**Comment by mit-mit** [comment]
@MetalDent thanks for the contribution! Please see feedback in the above review link

**Comment by MetalDent** [comment]
> Review in https://dart-review.googlesource.com/c/sdk/+/108180

Okay, so you don't want me to make a separate class?

**Comment by lrhn** [comment]
The extra `List` class won't work, there is already one `List` class declared in that library. The only issue is that the existing `List` class inherits the `operator==` method from `Object`, including the documentation.
By adding an abstract `operator==` method to the existing `List` class, we can add a new documentation for the method, without changing the inherited implementation.

**Comment by lrhn** [comment]
Looks good!
Thanks.

**Pull request closed without merging**
