### PR TITLE
Convert paths for mock SDK libraries to fix tests on Windows

### PR DESCRIPTION
**Pull request by DanTup**
The other lines on this method are calling `provider.convertPath` around their paths but these ones do not, which is causing almost all analysis server tests to fail on Windows (for me - I can't explain them not
failing builds). This causes the hard-coded paths like `/lib/core/core.dart` to be fixed up to `C:\lib\core\core.dart` which is what the server is looking for (because at the other end the paths *have* been fixed up).

See #32226.

### CODE REVIEW

**Comment by DanTup** [comment]
@bwilkerson @scheglov This fixes a large number of the tests for me, and the fix looks reasonable (other code in this method *is* calling this convert).

I'll dig into the remaining failures; though we should definitely look at why this wasn't causing failures in the build processing in case they're not running correctly (or the results not being interpreted correctly).

**Comment by DanTup** [comment]
I'm working through remaining failures and one is this:

```text
0:10 +498 -21: analysis_server | analysis | OldAnalysisOptionsFileNotificationTest | test_error_filter [E]
  FileSystemException(path=\lib\core\core.dart; message=File "\lib\core\core.dart" does not exist.)
  package:analyzer/file_system/memory_file_system.dart 440:7         _MemoryFile.readAsStringSync
  package:analyzer/src/source/source_resource.dart 94:46             FileSource.contentsFromFile
  package:analyzer/src/source/source_resource.dart 78:14             FileSource.contents.<fn>
```

It's possible (likely) this is a new failure as a result of this change. Looks like this one would've worked with the old code. So, don't merge this - let's wait until I've got *all* tests passing and we can review all changes together.

**Comment by bwilkerson** [comment]
When you upload a PR to Github, it automatically gets copied to Gerrit. (In this case, it's https://dart-review.googlesource.com/c/sdk/+/42300.) If you upload a patch, it get's copied over too. Unfortunately, comments don't get copied over, and so I didn't see your "don't merge this" request. (I'm trying an experiment to see whether I can abort the commit.)

Do you get notification of where the PR was copied to?

I've re-pinged the engprod team, but if they can't get you the access you need to Gerrit, then we'll have to figure out a process that works better.

**Comment by DanTup** [comment]
@bwilkerson Ah, doh!

I did get an email from Gerrit, and it looks like I can add comments there (but not edit some things like labels):

Gerrit

I'm slowly working through the remaining failures so I might have all tests passing soon, so I'll leave it to you whether you want to back this out or wait for that. There are a *lot* of path-related changes in the tests. Is there a way to confirm they're running correctly somewhere, as I'm not entirely sure how these weren't showing up (and if they weren't running correctly, we definitely want to get that fixed up).

**Comment by DanTup** [comment]
@bwilkerson I'm down to:

3999 passes
327 failures

Got about an hour left today, so probably these won't all be fixed. If you want me to send a PR that reverts the above and we can re-review when we're at 100% passes locally, let me know. Btw - I'm on Hangouts with the same email address you have for me (tuppeny.com - it's a Google account) if more convenient.

**Comment by bwilkerson** [comment]
> I'll leave it to you whether you want to back this out or wait for that.

The CL wasn't merged because of the test failures, so there's nothing to back out.

> Is there a way to confirm they're running correctly somewhere ...

If you open the build [console](https://build.chromium.org/p/client.dart/console) you'll see all of the build bots that are running. Under the group heading "analyzer", there are seven bots: one smoke test linux bot, three non-strong mode bots, and three strong-mode bots, one bot for each platform (mac, linux, and windows).

The top-most row of colored rounded rectangles indicates the status of the last run on the bot. Each of the other rows indicates the status for a particular run, most recent at the top and recent history below that.

If you click on the bar for a recent run of the windows bot (for example), you'll get a pop-up menu showing all of the individual steps in the build and test run.

If you select an item from the menu, such as "analysis server unit tests", it will open the log for that run (for example, [mac log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-mac10.11-release-strong-be%2F6354%2F%2B%2Frecipes%2Fsteps%2Fanalysis_server_unit_tests%2F0%2Fstdout)). There's a bunch of output listing the status of each test, and above that a summary that says that there are 173 tests (it counts each `*_test.dart` file as a single test, even though each file typically contains many tests, so we actually have more tests than that) and that 2 will be skipped. (I'm not sure why they're skipped. That information ought to be in the status file, but I haven't looked.)

However, if you look at the corresponding log file for the Windows bot ([windows log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-win7-release-strong-be%2F6863%2F%2B%2Frecipes%2Fsteps%2Fanalysis_server_unit_tests%2F0%2Fstdout)), it says that there are 173 tests and that 172 of them will be skipped. The remaining test ran successfully.

It appears that we're not running the analysis server tests on Windows. I hadn't realized that, but it explains why there's no bot failure despite the seriously broken tests.

When you've finished cleaning up the tests, we need to remember to re-enable those tests so that we can catch regressions! We can even re-enable them on a file-by-file basis if we don't get everything cleaned up all at once.

**Comment by DanTup** [comment]
> The CL wasn't merged because of the test failures, so there's nothing to back out.

Yeah, I just saw that I seem to have introduced the exact thing I fixed on Windows, on Linux :/

Once I've got Windows passing I'll take a look at what's happened. If anything, I expected the paths to be much more resilient with these changes.

> It appears that we're not running the analysis server tests on Windows. I hadn't realized that, but it explains why there's no bot failure despite the seriously broken tests.

Aha! Thanks for digging. I'll be sure to make sure we don't forget once I'm done 😄

**Comment by DanTup** [comment]
@bwilkerson Trying to run my changes on Mac & Linux (since it looked like there were linux failures?) but on my Mac I get a bunch of failures and the test run crashes - I don't know if these might be skipped tests (I can't find how to tell which tests are supposed to be skipped or whether I can do a run also skipping them):

```text
01:25 +4247 -82: analysis_server | spec | SpecTest | test_specHasBeenGenerated
All generated files up to date.
Unhandled exception:
NoSuchMethodError: Class '_RootZone' has no instance method 'bindCallback' with matching arguments.
Receiver: Instance of '_RootZone'
Tried calling: bindCallback(Closure: () => dynamic, runGuarded: false)
Found: bindCallback(() => dynamic) => ZoneCallback
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Pool._onResourceReleaseAllowed (package:pool/pool.dart:187:24)
#2      PoolResource.allowRelease (package:pool/pool.dart:273:11)
#3      Engine.run.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/runner/engine.dart:276:24)
<asynchronous suspension>
#4      new Future.sync (dart:async/future.dart:222)
#5      Pool.withResource.<anonymous closure> (package:pool/pool.dart:127:18)
#6      _RootZone.runUnary (dart:async/zone.dart:1381)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:662)
#10     _Future._completeWithValue (dart:async/future_impl.dart:477)
#11     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

The results are the same with/without my changes. Any ideas?

**Comment by DanTup** [comment]
@bwilkerson I got things up and running on an Ubuntu VM and I see 100% passes both on `master` and on my branch. I'm not sure how to explain the failures :(

I'm gonna push those fixes from that branch into this PR so we can at least run the latest (I've made many more fixes) and review; but I'm not sure what to make of the differences between my Linux box and that build.

**Pull request closed without merging**
