### PR TITLE
Clarified that toJson doesn't work when provided as an extension

### PR DESCRIPTION
**Pull request by chonghorizons**
only a documentation addition.

### CODE REVIEW

**Comment by mit-mit** [comment]
Review CL is https://dart-review.googlesource.com/c/sdk/+/222403

@chonghorizons can you please take a look at that (sorry, we review SDK changes in a different tool than here on Github)

**Comment by chonghorizons** [comment]
> Review CL is https://dart-review.googlesource.com/c/sdk/+/222403
> 
> @chonghorizons can you please take a look at that (sorry, we review SDK changes in a different tool than here on Github)

I think the proposed change to

 ... as a dynamic method call.

is fine and accurate.

I'm not sure how you run your merges. Should I modify my PR patch-1 branch on github or will someone make the change directly on googlesource.com? I tried to comment on your code review tool, but I might not have permissions.

**Comment by mit-mit** [comment]
You just push changes to this PR, and then they get automatically sync'ed to the associated dart-review.

**Comment by mit-mit** [comment]
@chonghorizons any updates? This PR will be closed in a few days unless hear from you.

**Comment by mit-mit** [comment]
Yes, that would be fine. Please link to his PR when creating the new one.

**Pull request closed without merging**
