### PR TITLE
[vm] add compile-time error when ffi @Array got non-positive input.

### LINKED ISSUE #45540: No error in CFE and Analyzer for Array.multi() with negative dimensions
The following code produces no compile errors in both analyzer and CFE
```dart
import "dart:ffi";

class MyStruct extends Struct {
  @Array.multi([-1])  // no error
  external Array<Uint8> a0;
}

void main() {
  MyStruct? ms = null;
}
```
`Dart SDK version: 2.13.0-165.0.dev (dev) (Thu Mar 25 02:53:52 2021 -0700) on "windows_x64" `

cc @dcharkes

### PR DESCRIPTION
**Pull request by lfkdsk**
try to fix https://github.com/dart-lang/sdk/issues/45540

### CODE REVIEW

**Comment by dcharkes** [comment]
Thanks @lfkdsk ! 😃 

See my review at https://dart-review.googlesource.com/c/sdk/+/196246.

**Comment by dcharkes** [comment]
Please rebase and fix the merge conflicts:

```
FAILED: vm_platform_strong.dill vm_outline_strong.dill 
python3 ../../build/gn_run_binary.py compiled_action /b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=86e1eb9101 --packages=/b/s/w/ir/cache/builder/sdk/.packages --dfe=/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/compile_platform.dart dart:core -Ddart.vm.product=false -Ddart.isVM=true --nnbd-agnostic --single-root-scheme=org-dartlang-sdk --single-root-base=/b/s/w/ir/cache/builder/sdk/ org-dartlang-sdk:///sdk/lib/libraries.json vm_outline_strong.dill vm_platform_strong.dill vm_outline_strong.dill
Command failed: /b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=86e1eb9101 --packages=/b/s/w/ir/cache/builder/sdk/.packages --dfe=/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /b/s/w/ir/cache/builder/sdk/pkg/front_end/tool/_fasta/compile_platform.dart dart:core -Ddart.vm.product=false -Ddart.isVM=true --nnbd-agnostic --single-root-scheme=org-dartlang-sdk --single-root-base=/b/s/w/ir/cache/builder/sdk/ org-dartlang-sdk:///sdk/lib/libraries.json vm_outline_strong.dill vm_platform_strong.dill vm_outline_strong.dill
output: ../../pkg/vm/lib/transformations/ffi_definitions.dart:340:28: Error: The getter 'name' isn't defined for the class 'Name'.
 - 'Name' is from 'package:kernel/ast.dart' ('../../pkg/kernel/lib/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
                    f.name.name.length,
                           ^^^^
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8849268844498817648/+/u/build_dart/stdout

**Comment by dcharkes** [comment]
I left some small final comments on https://dart-review.googlesource.com/c/sdk/+/196246. Then we're ready to merge! 😃

**Comment by dcharkes** [comment]
Some tests are failing: https://dart-ci.firebaseapp.com/cl/196246/7, the analyzer tests in static_checks_test should start succeeding after we land the other PR (those tests are both run against the CFE and analyzer, but the other CL contains the analyzer patch).

For the CFE messages test you'll need a status file entry as in https://dart-review.googlesource.com/c/sdk/+/183640/31/pkg/front_end/messages.status

Let me know if you need help running these tests locally. (All failing tests should have a reproduction command.)

**Comment by lfkdsk** [comment]
I rebase the master branch, so the error in the analyzer section should be gone. I also added a flag in `messages.status` to indicate that the analyzer test was skipped.
However, I don't seem to have the permission to manually trigger CI, so I wondered how to trigger these two tests locally?

I have tried these commands：

```
./tools/test.py -mrelease --arch=x64 --runtime=vm ffi_2

```

and

```
 python3 -u tools/test.py -ncfe-unittest-asserts-release-mac "pkg/_fe_analyzer_shared|pkg/analyzer|pkg/front_end"
```

**Comment by dcharkes** [comment]
Landed. Thanks @lfkdsk!

**Comment by lfkdsk** [comment]
thx for cr ~ @dcharkes

**Pull request closed without merging**
