### PR TITLE
Spelling sdk

### PR DESCRIPTION
**Pull request by jsoref**
This change is scoped to sdk with any files that happened to be changed in those commits per https://github.com/dart-lang/sdk/issues/50754, it's <50 files.

### CODE REVIEW

**Comment by eernstg** [comment]
https://dart-review.googlesource.com/c/sdk/+/278530

**Comment by athomas** [comment]
Mostly LGTM, two long lines. See https://dart-review.googlesource.com/c/sdk/+/278530 for details.

**Comment by athomas** [comment]
CI has additional failures caused by these changes (some golden files need to be regenerated):
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8791554537306950977/+/u/test_results/new_test_failures__logs_

Let me know in case that doesn't work for you.

**Comment by jsoref** [comment]
That specific links yields this:
image

I've tried to address the pieces that I could puzzle through. If you could do the rest, that'd be great...

**Comment by athomas** [comment]
> That specific links yields this: image
> 
> I've tried to address the pieces that I could puzzle through. If you could do the rest, that'd be great...

Np, GitHub somehow dropped the trailing slash from the link (now fixed). I can run the tooling on your behalf.

**Pull request closed without merging**
