### PR TITLE
Fix: Typo in elementAt() method description

### PR DESCRIPTION
**Pull request by awulkan**

### CODE REVIEW

**Comment by mit-mit** [comment]
Code review is https://dart-review.googlesource.com/c/sdk/+/130182

**Comment by mit-mit** [comment]
Thanks for contributing @awulkan, feedback posted in the above code review link

**Comment by awulkan** [comment]
@mit-mit Done.

**Comment by mit-mit** [comment]
Thanks @awulkan, merging shortly

**Pull request closed without merging**
