### PR TITLE
Fixed various typos in a lot of files

### PR DESCRIPTION
**Pull request by anisalibegic**
Quite large amount of typos spotted and fixed mostly in comments.

### CODE REVIEW

**Comment by mit-mit** [comment]
Review in https://dart-review.googlesource.com/c/sdk/+/251902

**Comment by mit-mit** [comment]
Thanks very much for this comprehensive contribution @anisalibegic! There are a few review comments for you in the review tool (see link in my previous comment); can you please take a look at those?

**Comment by anisalibegic** [comment]
> Thanks very much for this comprehensive contribution @anisalibegic! There are a few review comments for you in the review tool (see link in my previous comment); can you please take a look at those?

For that one comment I've created a PR on [microsoft/vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) repo.
PR: https://github.com/microsoft/vscode-languageserver-node/pull/1036

Is there anything else I can do?

**Comment by mit-mit** [comment]
Great that you made the PR to the code repo upstream. For now can you undo the change to `pkg/analysis_server/tool/lsp_spec/lsp_meta_model.json` in this PR? Then we'll pick up the change when it's changed upstream.

As for the second review comment around US/British spelling, I believe there was a request to change `consistent behaviour of` to `consistent behavior of`.

When you make those changes, just push them here to your github PR. Then they will get mirrored into the code review, and we can resolve the comments there and land it.

**Comment by anisalibegic** [comment]
> Great that you made the PR to the code repo upstream. For now can you undo the change to `pkg/analysis_server/tool/lsp_spec/lsp_meta_model.json` in this PR? Then we'll pick up the change when it's changed upstream.
> 
> As for the second review comment around US/British spelling, I believe there was a request to change `consistent behaviour of` to `consistent behavior of`.
> 
> When you make those changes, just push them here to your github PR. Then they will get mirrored into the code review, and we can resolve the comments there and land it.

I reverted a change to `pkg/analysis_server/tool/lsp_spec/lsp_meta_model.json` and changed `behaviour` to `behavior`.

**Comment by mit-mit** [comment]
Perfect, thanks. I'll get the last few approvals on the review, and get this landed shortly!

**Pull request closed without merging**
