### PR TITLE
Remove emphasis on client-side and UI in the readme

### PR DESCRIPTION
**Pull request by MohiuddinM**
Considering the growing popularity of dart on backend and tooling side, this PR removes specific emphasis on client and UI. 

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.

Note that this repository uses Gerrit for code reviews. Your pull request will be automatically converted into a Gerrit CL and a link to the CL written into this PR. The review will happen on Gerrit but you can also push additional commits to this PR to update the code review.
</details>

### CODE REVIEW

**Comment by Cat-sushi** [comment]
README.md and https://dart.dev/ should be consistent each other.

**Comment by mraleph** [comment]
@mit-mit ping?

**Comment by mraleph** [comment]
I am going to close this for now though we are certainly going to review and update the language at some later point.

**Pull request closed without merging**
