### PR TITLE
Fix dart2js in the dev branch.

### PR DESCRIPTION
**Pull request by harryterkelsen**
I wasn't sure how to create a commit that only applied to the dev branch with 'git cl' so I just did it on my fork. Please merge this into dev or let me know the right way to create this commit so you can merge it into dev. Thanks!

### CODE REVIEW

**Comment by sigmundch** [comment]
@hterkelsen I think one option is to do `git cl upload origin/dev` - that will tell rietveld to use `origin/dev` as the base CL.  `git cl land` might support that too, but I haven't tried that.

**Comment by whesse** [comment]
Yes, you would make a branch with origin/dev, but you don't want to land it, because we do that with a merge commit to make the new version.  We would want a new branch, based on dev, in the main repo, with this commit on it.  Then I can cherry-pick it to dev in a new version.  But this is fine as is - I'll do it in the next merge.

**Comment by hterkelsen** [comment]
My bad, I had not seen https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-dev-channel
This could have been avoided by just including this patch in the original merge request. I'll follow those instructions in the future. Thanks Bill!

**Comment by hterkelsen** [comment]
You can merge this instead: https://codereview.chromium.org/1308343003/

**Comment by hterkelsen** [comment]
Closing this since the Rietveld patch was merged instead.

**Pull request closed without merging**
