### PR TITLE
Added option to dartanalyzer to treat lints as errors.

### LINKED ISSUE #25977: Fatal lints
I'd like to be able to make lints fatal (non-zero exit code) without writing a wrapper to scrape the output. A `--fatal-lints` would do the trick as well as something in `.analysis_options`.

### PR DESCRIPTION
**Pull request by pylaligand**
Fixes #25977

### CODE REVIEW

**Comment by bwilkerson** [comment]
lgtm

**Comment by pylaligand** [comment]
Thanks for the review! I don't have write access so I can't merge the change myself.

**Comment by pylaligand** [comment]
Argh, just realizing right now that you don't use GitHub PRs. Do you want me to resent this on codereview.chromium.org?

**Comment by bwilkerson** [comment]
No. I'm fine with a PR as long as it's fairly short (the UI is hard to deal with for large changes).

Have you signed the CLA (as described on https://github.com/dart-lang/sdk/wiki/Contributing)?

**Comment by pylaligand** [comment]
Yeah the CLA is signed (I work for Google btw). There's an automated check for it on this page.

**Comment by bwilkerson** [comment]
So there is. Missed that.

**Pull request merged**
