### PR TITLE
Uri: Complete missing hashCode documentation.

### PR DESCRIPTION
**Pull request by ybakos**
The documentation comment for the Uri hashCode property is incomplete.

Complete the description of the hashCode property.

### CODE REVIEW

**Comment by ybakos** [comment]
Thank you for all things **dart-lang**. Please let me know if you would prefer this PR on a different branch besides _dev_, or if I should use the formal patch workflow.

(Doing this as a PR demo for students, getting started in open source contributions by fixing documentation.)

**Comment by kevmoo** [comment]
I think this sounds okay...

**Comment by athomas** [comment]
Thanks for your contribution!

Please do rebase your change on the master branch. We are unable to merge this until it is based on master. Our PR automation looks for the merge base on the master branch, where it can't find it. We also do not land changes directly on the dev branch, but merge from master to dev every 4 hours.

**Comment by athomas** [comment]
Hmm, I noticed you also created #44363. Both of these PRs use the wrong base branch (`dev` instead of `master`). On this PR, I tried changing that but that confuses GitHub. Perhaps, the easiest would be to change the base branch on #44363, which I can't do myself (perhaps because the PR is closed).

**Comment by lrhn** [comment]
I changed the base for the PR. That does cause a lot of noise, but the actual change looks OK.

**Comment by athomas** [comment]
> I tried just hanging the base for the PR directly in github. Didn;'t work for me.

Yes, I did the same and it also didn't work for me. But it may work on #44363.

**Review by kwalrath — APPROVED** [review]
Words look good.

**Comment by ybakos** [comment]
Yikes, rebasing onto master created a mess on my end - I likely made a mistake. Please see #44371 which is a PR of a feature branch off of _master_, and this PR is for a merge into _master_.

/cc @kevmoo @athomas @lrhn @kwalrath

**Pull request closed without merging**
