### PR TITLE
Add a performance benchmark for the angular analyzer plugin

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**
It doesn't look like this is very easy to add to our own repo. Also noticed that flutters benchmark is in here even though they have a separate codebase for their analyzer plugins. That said, if there should indeed be a way to commit this to the angular analyzer repo and that would be preferred, I can definitely look into that.

### CODE REVIEW

**Comment by scheglov** [comment]
It seems that I didn't explain it in right words initially. The existing performance tests are not tests for Flutter, they are tests for Analysis Server performance on the Flutter codebase.

**Comment by scheglov** [comment]
The benchmark looks OK, although the one for changing HTML is probably not very useful.

Whether or not to put the benchmark into Analysis Server is another question.
I would prefer not to.
@bwilkerson might also want to see this.

**Comment by MichaelRFairhurst** [comment]
Ah! Thought the arrangement was a little strange.

Is there a way for me to use this infrastructure though from my own project? Since I'm using files in `/test` and `/benchmark` instead of `lib`. I tried using hardcoded relative paths, but that also seemed to have some issues.

**Comment by bwilkerson** [comment]
I might be missing something, but I think this code would run the main in analysis_server's bin, and that main doesn't install the angular2dart plugin, so I don't think you'd be benchmarking your plugin.

> Is there a way for me to use this infrastructure though from my own project?

Unfortunately, no. A package can only import from the 'lib' directory of another package. And then there's the problem that we don't publish the 'analysis_server' package.

**Comment by MichaelRFairhurst** [comment]
> I might be missing something, but I think this code would run the main in analysis_server's bin, and that main doesn't install the angular2dart plugin, so I don't think you'd be benchmarking your plugin.

Yes, it runs the bin. If you have our plugin installed, it will replace the analysis server bin, so it will run our analysis code.

As an extra nicety, this allows be to run these benchmarks with and without my plugin by switching out the bin.

**Comment by MichaelRFairhurst** [comment]
Want to check on what direction we should take with this.

If merging isn't the right option, I can leave it as a branch in my fork for us to use, or maybe we could extract the benchmarking stuff into a library so that I can use it from the angular analysis repo.

Or alternative suggestions welcomed!

**Review by bwilkerson — APPROVED** [review]
Given that the benchmark doesn't introduce a dependency on Angular, I have no problems merging it in.

**Pull request merged**
