### PR TITLE
Expand the range of trace line numbers

### PR DESCRIPTION
**Pull request by Yogaflre**
00~999.
Solve the problems that more than 100 lines cannot be translated.

### CODE REVIEW

**Comment by Yogaflre** [comment]
CLA signed.

**Review by sstrickl — CHANGES_REQUESTED** [review]
I'd suggest going ahead and changing it from `{2}` to `+` instead to allow any length number here, because the chance that any non-stacktrace line in the parsed input matches this regexp is minimal as it is.

While I expect stack traces with 4 or more digit line numbers will be... unlikely, might as well allow them while we're making the change so we don't have to extend it again in the future. :)

**Comment by mraleph** [comment]
Gerrit CL: https://dart-review.googlesource.com/c/sdk/+/224560

**Comment by Yogaflre** [comment]
> I'd suggest going ahead and changing it from `{2}` to `+` instead to allow any length number here, because the chance that any non-stacktrace line in the parsed input matches this regexp is minimal as it is.
> 
> While I expect stack traces with 4 or more digit line numbers will be... unlikely, might as well allow them while we're making the change so we don't have to extend it again in the future. :)

I am not familiar enough with this part of the code. Thanks for your suggestions.

**Comment by sstrickl** [comment]
Thanks for the fix! Have approved the Gerrit CL and put in the commit queue, so should land shortly.

**Comment by sstrickl** [comment]
I've published version 0.4.5 of the `native_stack_traces` package, which includes this fiix.

**Pull request closed without merging**
